### PR TITLE
Combine approach from oc_sampler_probability to sample whole traces

### PR DESCRIPTION
**Pull request by derekkraan**
Hi @garthk,

I have been working on this a little bit. I believe a better approach to sampling would be to use the same approach taken in `:oc_sampler_probability`, which does it on the basis of the trace_id in a predictable way. Given that trace_ids are randomly generated, this should result in the same sample rates, but it should result (if you use the same sample_rate for all the events in your trace...) in sampling whole traces.

https://github.com/census-instrumentation/opencensus-erlang/blob/master/src/oc_sampler_probability.erl

### CODE REVIEW

**Comment by garthk** [comment]
Sending the trace if trace_id mod sample_rate is 0 makes sense to me. Can't review the code right now; chase me if you don't hear back this year?

**Comment by garthk** [comment]
Haha they just made my entire OT exporter redundant! https://www.honeycomb.io/blog/announcing-honeycomb-support-for-event-ingestion-with-otlp/

Update: gRPC over HTTP/2 only so it might not suit all environments. It might suit enough to put the OT exporter on our support hierarchy, but.

**Comment by derekkraan** [comment]
Hey @garthk I was supposed to ping you if you didn't get to reviewing this in 2020 :D

**Comment by garthk** [comment]
Thanks for the prompt, @derekkraan!

I'm surprised by less-than-threshold comparison… @tsloughter got any specification references for the code in OC-erlang? I was expecting `TraceId mod SampleRate` where the sample rate is a non-negative integer. Leans me towards taking more config (ugh) so people can plug in whatever “does this pass?” mechanism matches the rest of their environment.

**Comment by tsloughter** [comment]
Since the distribution is random you can essentially split the set of possible trace ids into those in the sample range and those not, removing the need for doing a `mod` every time.

**Comment by garthk** [comment]
I see how that works, sure. Just not sure mod is so expensive we should
avoid calling it once per span.

Every example I've seen of trying to line up sampling so 1:100 and 1:10
spans in the same trace show up together in 1% of traces, uses modulo
arithmetic to do so: it's intuitively obvious with a chain of zeroes at the
back end. We might well get the same effect with the threshold, but for
some reason I'm having trouble nutting it out. Ne'er mind: we'll need at
least one such implementation to be compatible. Just need to be able to
plug in alternatives for when everything else is doing mod math.

**Pull request closed without merging**
